### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by roylisto** [ngurahyudi/messenger#1]
Hi @ngurahyudi, I am Roy from AdaKerja.

I will be reviewing your submission, but first of all, is there any guidance for me to set up your code in my local?
What are the prerequisites, can you update your readme?

Thank you

**Comment by ngurahyudi** [comment]
Hi Roy, nice to hear from you.. I'll update the readme file soon. Thank you

**Comment by ngurahyudi** [comment]
Hi @roylisto i've updated the readme and I hope you got it works, please message me if you need more assist

**Comment by roylisto** [comment]
Thank @ngurahyudi, did you deploy your API to Heroku or somewhere?

**Comment by ngurahyudi** [comment]
Hi @roylisto no I don't, i just run it on my local machine

**Comment by roylisto** [comment]
Alright, I'll continue to review your submission this week, but please let me know if you had a live working demo that we can test later because this also has a bonus point if you have that :)
Thanks!

**Comment by ngurahyudi** [comment]
@roylisto I've try to do that by using amazon elastic beanstalk and codepipeline to provide CI development but unfortunately I cannot provide the ssl certificate since facebook only allow connection over https. If you say it will be a bonus point then i will try my best. Thanks

**Comment by roylisto** [comment]
Cool! deploying to Heroku would be simpler imho

**Comment by ngurahyudi** [comment]
@roylisto I never touch Heroku before LOL, will try!

**Comment by roylisto** [comment]
Hi, after reviewing your work, here is my review and question

Review:
[+] Good code structure, using MVC pattern
[+] Use typescript
[+] Have migration and seed files
[+] Use Jsdocs
[-] Endpoints not tested properly, only check whether the service is defined or not
[-] Some unused leftover code from refactoring

Questions:
1. Why do you choose MySQL and not NoSQL as the database?
2. How can you scale your application?
3. How you can test your endpoints properly? and would you mind fixing that?

Please address my reviews and questions so we can proceed to the next step :)
(Would be better if you have a demo, but it's okay if you can't host it)

Thank You

**Comment by ngurahyudi** [comment]
hi @roylisto so easy to deploy to heroku LOL thanks for your advice
https://messenger-bot-x.herokuapp.com/webhook 
To test whether it works or not I must register your fb developer account as developer or tester of my app.
1. I've been thinking about using mongodb at the beginning but It might take much time to code the boilerplate from the begining (it's been so long i'm not using it).
2. maybe i can make it as containerized app by using docker and k8s as the orchestrator
3. I'm sorry not providing the unit test, i will try to update it

Thank you

**Comment by roylisto** [comment]
Cool!, no worry I just want to test your list message endpoint from Heroku, would you mind sharing the URL?

**Comment by ngurahyudi** [comment]
Absolutely, here it is : https://messenger-bot-x.herokuapp.com/summary

**Comment by roylisto** [comment]
Thanks, let me know once you add the unit/integration test, the rest is good to me

**Comment by ngurahyudi** [comment]
Sure @roylisto I'm working on it..

**Comment by ngurahyudi** [comment]
> Thanks, let me know once you add the unit/integration test, the rest is good to me

Hi @roylisto I just pushed the commits contains the tests, you owe me 2 bonuses: make it online & provide the test LOL

**Comment by roylisto** [comment]
Sure let me check hahaha

**Comment by ngurahyudi** [comment]
done
